#!/usr/bin/env sh

yabai -m config                               \
    menubar_opacity             0.75          \
    mouse_follows_focus         on            \
    focus_follows_mouse         off           \
    display_arrangement_order   default       \
    window_placement            second_child  \
    window_origin_display       default       \
    window_zoom_persist         on            \
    insert_feedback_color       0xffd75f5f    \
    split_ratio                 0.50          \
    split_type                  auto          \
    auto_balance                off           \
    top_padding                 8             \
    bottom_padding              8             \
    left_padding                8             \
    right_padding               8             \
    window_gap                  10            \
    layout                      bsp           \
    mouse_modifier              alt           \
    mouse_action1               move          \
    mouse_action2               resize        \
    mouse_drop_action           swap

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Microsoft Outlook$" manage=off
yabai -m rule --add app="^Mattermost$" manage=off
yabai -m rule --add app="^Preview$" manage=off

# intellij compability - popup windows
yabai -m rule --add app="^IntelliJ IDEA$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="( – )" manage=on

yabai -m rule --add app="^Obsidian$" space=3

borders style=round active_color=0xff65bf00 inactive_color=0xff494d64 width=5.0 &
echo "Yabai configuration loaded"

